### ISSUE TITLE
[ERROR] direct_handler.handler KeyError(None,)

### ISSUE THREAD

**Issue by zjhzxhz** [XX-net/XX-Net-dev#4]
Error Log:

```
May 03 20:18:13.116 - [ERROR] direct_handler.handler KeyError(None,) www.google.com /js/bg/bjEnSSRtkQDmV5c2Pm_sWdo8WoIWRicVzzTAt_BvtSY.js , retry...
May 03 20:18:13.117 - [ERROR] Except stack:Traceback (most recent call last):
  File "/media/Data/Applications/XX-Net/code/default/gae_proxy/local/direct_handler.py", line 95, in handler
    response = fetch(method, host, url, headers, body)
  File "/media/Data/Applications/XX-Net/code/default/gae_proxy/local/direct_handler.py", line 50, in fetch
    ssl_sock = https_manager.get_ssl_connection(host)
  File "/media/Data/Applications/XX-Net/code/default/gae_proxy/local/connect_manager.py", line 507, in get_ssl_connection
    ret = self.host_conn_pool[host].get_nowait(only_h1=True)
  File "/media/Data/Applications/XX-Net/code/default/gae_proxy/local/connect_manager.py", line 116, in get_nowait
    return self.get(block=False, only_h1=only_h1)
  File "/media/Data/Applications/XX-Net/code/default/gae_proxy/local/connect_manager.py", line 110, in get
    item = self._get(only_h1=only_h1)
  File "/media/Data/Applications/XX-Net/code/default/gae_proxy/local/connect_manager.py", line 133, in _get
    self.pool.pop(fastest_sock)
KeyError: None
```

Env: ArchLinux + Python 2.7.11+

**Comment by xxnet** [comment]
同 ​#3165
已经提交新代码，你试试master上的版本

**Comment by zjhzxhz** [comment]
表示ArchLinux已经被我卸了 - -|||

**Comment by zjhzxhz** [comment]
I've download the latest code from master, but the problem still exists.
(I'm using Debian now)

Here's the error log:

```
May 03 16:09:34.094 - [ERROR] direct_handler.handler KeyError(None,) www.google.com /_/chrome/newtab?espv=2&ie=UTF-8 , retry...
May 03 16:09:34.094 - [ERROR] Except stack:Traceback (most recent call last): File "/media/Data/Applications/XX-Net/code/default/gae_proxy/local/direct_handler.py", line 95, in handler response = fetch(method, host, url, headers, body) File "/media/Data/Applications/XX-Net/code/default/gae_proxy/local/direct_handler.py", line 50, in fetch ssl_sock = https_manager.get_ssl_connection(host) File "/media/Data/Applications/XX-Net/code/default/gae_proxy/local/connect_manager.py", line 544, in get_ssl_connection ret = self.new_conn_pool.get(True, self.max_timeout, only_h1=only_h1) File "/media/Data/Applications/XX-Net/code/default/gae_proxy/local/connect_manager.py", line 110, in get item = self._get(only_h1=only_h1) File "/media/Data/Applications/XX-Net/code/default/gae_proxy/local/connect_manager.py", line 133, in _get self.pool.pop(fastest_sock) KeyError: None
```

BTW, the application running on Windows crashes all the time (maybe 3 hours per time?). 
It's annoying.

Sorry, I cannot type Chinese yet, because I haven't install the Chinese input.

**Comment by zjhzxhz** [comment]
Wait...
It seems that I didn't upgrade to the latest version.
